services:
    flask-app:
        build: .
        ports:
          - "5000:5000"

    mysql:
     image: mysql:8.0.39
     volumes:
       - db_data:/var/lib/mysql:rw
       - ./db-init:/docker-entrypoint-initdb.d/:rw
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: flask
       MYSQL_USER: user
       MYSQL_PASSWORD: password

volumes:
    db_data: