apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: "victorcardonaf/my-flask-app:1.4"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: test
spec:
  ports:
  - port: 5000
  selector:
    app: flask-app