apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mysql.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysql.pvPath }}
